import { useMemo, useState } from 'react';
import type { BreakdownRow } from '../../shared/analytics';
import { currencyFormatter, numberFormatter } from '../lib/format';

type BreakdownTableProps = {
  rows: BreakdownRow[];
};

type SortKey = keyof BreakdownRow;
type SortDirection = 'asc' | 'desc';

const columns: Array<{ align?: 'left' | 'right'; help: string; key: SortKey; label: string }> = [
  {
    align: 'left',
    help: 'The customer, channel, branch, product, or operating group being compared.',
    key: 'name',
    label: 'Business segment',
  },
  {
    help: 'How many users, customers, orders, or records are attached to this segment.',
    key: 'users',
    label: 'Activity volume',
  },
  {
    help: 'The share of activity that completed the desired outcome, such as purchase, signup, or successful transaction.',
    key: 'conversion',
    label: 'Success rate',
  },
  {
    help: 'Total value generated by the segment in the current analysis window.',
    key: 'revenue',
    label: 'Revenue impact',
  },
  {
    help: 'The slowest normal experience for the top 5% of requests. Lower is better for service quality.',
    key: 'latency',
    label: 'Service delay',
  },
];

function compareRows(a: BreakdownRow, b: BreakdownRow, key: SortKey) {
  if (key === 'name') {
    return a.name.localeCompare(b.name);
  }

  return a[key] - b[key];
}

function getSegmentContext(name: string) {
  const normalized = name.trim().toLowerCase();
  const knownContexts: Record<string, { area: string; meaning: string; tooltip: string }> = {
    organic: {
      area: 'Marketing acquisition channel',
      meaning: 'Visitors or customers gained through unpaid search, content, SEO, or natural discovery.',
      tooltip: 'Organic is a marketing/acquisition segment. It usually means people found the business without a paid advert, such as search engines, content, brand awareness, or direct discovery.',
    },
    paid: {
      area: 'Marketing acquisition channel',
      meaning: 'Visitors or customers gained through paid adverts, campaigns, sponsored posts, or promoted placements.',
      tooltip: 'Paid is a marketing/acquisition segment. It should be judged against ad spend, conversion rate, revenue, and customer acquisition cost.',
    },
    referral: {
      area: 'Relationship and partner channel',
      meaning: 'Visitors or customers coming from partners, links, recommendations, affiliates, or other referring sources.',
      tooltip: 'Referral is usually a relationship, partner, or word-of-mouth channel. It helps show whether partners, recommendations, affiliates, or external links are bringing useful demand.',
    },
    direct: {
      area: 'Brand demand channel',
      meaning: 'Visitors or customers who came directly, often from saved links, typed URLs, returning users, or strong brand recall.',
      tooltip: 'Direct is usually a brand-demand segment. It can reflect returning customers, known users, saved links, typed URLs, or traffic where the original source is not identified.',
    },
  };

  return knownContexts[normalized] ?? {
    area: 'Business segment',
    meaning: 'A grouped part of the data used to compare performance, demand, value, risk, or operational quality.',
    tooltip: `${name} is a segment from the selected dataset. Use it to compare whether this group contributes more value, has stronger outcomes, or needs operational attention than the others.`,
  };
}
function getSegmentRole(row: BreakdownRow, rows: BreakdownRow[]) {
  const topRevenue = Math.max(...rows.map((item) => item.revenue));
  const topConversion = Math.max(...rows.map((item) => item.conversion));
  const highestLatency = Math.max(...rows.map((item) => item.latency));

  if (row.revenue === topRevenue && row.conversion === topConversion) {
    return 'Primary growth engine';
  }

  if (row.revenue === topRevenue) {
    return 'Largest value driver';
  }

  if (row.conversion === topConversion) {
    return 'Strongest quality signal';
  }

  if (row.latency === highestLatency || row.latency > 120) {
    return 'Service risk to monitor';
  }

  return 'Stable supporting segment';
}

function summarizeSegments(rows: BreakdownRow[]) {
  if (rows.length === 0) {
    return null;
  }

  const totalUsers = rows.reduce((sum, row) => sum + row.users, 0);
  const totalRevenue = rows.reduce((sum, row) => sum + row.revenue, 0);
  const weightedConversion = totalUsers > 0 ? rows.reduce((sum, row) => sum + row.conversion * row.users, 0) / totalUsers : 0;
  const bestRevenue = rows.reduce((best, row) => (row.revenue > best.revenue ? row : best), rows[0]);
  const bestConversion = rows.reduce((best, row) => (row.conversion > best.conversion ? row : best), rows[0]);
  const slowest = rows.reduce((worst, row) => (row.latency > worst.latency ? row : worst), rows[0]);

  return {
    bestConversion,
    bestRevenue,
    slowest,
    totalRevenue,
    totalUsers,
    weightedConversion,
  };
}

export function BreakdownTable({ rows }: BreakdownTableProps) {
  const [sortKey, setSortKey] = useState<SortKey>('revenue');
  const [sortDirection, setSortDirection] = useState<SortDirection>('desc');

  const sortedRows = useMemo(() => {
    return [...rows].sort((a, b) => {
      const result = compareRows(a, b, sortKey);
      return sortDirection === 'asc' ? result : -result;
    });
  }, [rows, sortDirection, sortKey]);
  const summary = useMemo(() => summarizeSegments(rows), [rows]);

  const updateSort = (key: SortKey) => {
    if (key === sortKey) {
      setSortDirection((direction) => (direction === 'asc' ? 'desc' : 'asc'));
      return;
    }

    setSortKey(key);
    setSortDirection(key === 'name' ? 'asc' : 'desc');
  };

  return (
    <section className="panel table-panel">
      <div className="panel-header">
        <div>
          <p className="eyebrow">Segment performance insight</p>
          <h3>Where value, demand, and service quality differ</h3>
          <p>
            Compare each segment by activity volume, outcome rate, revenue impact, and service delay. In this view, Organic, Paid, Referral, and Direct are acquisition-channel segments used to understand marketing demand, relationship-driven traffic, brand demand, and operational service quality.
          </p>
        </div>
      </div>
      {summary ? (
        <div className="segment-summary-grid" aria-label="Segment analysis summary">
          <div>
            <span>Total value reviewed</span>
            <strong>{currencyFormatter.format(summary.totalRevenue)}</strong>
            <p>{numberFormatter.format(summary.totalUsers)} records or customers represented across all segments.</p>
          </div>
          <div>
            <span>Strongest outcome rate</span>
            <strong>{summary.bestConversion.name}</strong>
            <p>{summary.bestConversion.conversion.toFixed(1)}% success rate; weighted average is {summary.weightedConversion.toFixed(1)}%.</p>
          </div>
          <div>
            <span>Largest value driver</span>
            <strong>{summary.bestRevenue.name}</strong>
            <p>{currencyFormatter.format(summary.bestRevenue.revenue)} generated in the current view.</p>
          </div>
          <div>
            <span>Reliability watch</span>
            <strong>{summary.slowest.name}</strong>
            <p>{summary.slowest.latency}ms service delay; prioritize if customer experience matters.</p>
          </div>
        </div>
      ) : null}
      <div className="table-scroll">
        <table>
          <thead>
            <tr>
              {columns.map((column) => (
                <th className={column.align === 'left' ? 'align-left' : undefined} key={column.key}>
                  <button
                    aria-label={`Sort by ${column.label}`}
                    className={sortKey === column.key ? 'active' : undefined}
                    data-tooltip={column.help}
                    onClick={() => updateSort(column.key)}
                    type="button"
                  >
                    {column.label}
                    {sortKey === column.key ? <span>{sortDirection === 'asc' ? 'up' : 'down'}</span> : null}
                  </button>
                </th>
              ))}
              <th>Business meaning</th>
            </tr>
          </thead>
          <tbody>
            {sortedRows.length > 0 ? (
              sortedRows.map((row) => {
                const context = getSegmentContext(row.name);

                return (
                <tr key={row.name}>
                  <td>
                    <div className="segment-name-cell" data-tooltip={context.tooltip}>
                      <strong>{row.name}</strong>
                      <span>{context.area}</span>
                      <small>{context.meaning}</small>
                    </div>
                  </td>
                  <td>{numberFormatter.format(row.users)}</td>
                  <td>{row.conversion.toFixed(1)}%</td>
                  <td>{currencyFormatter.format(row.revenue)}</td>
                  <td>
                    <span className={row.latency > 120 ? 'latency-warning' : undefined}>{row.latency}ms</span>
                  </td>
                  <td>
                    <span className="segment-role">{getSegmentRole(row, rows)}</span>
                  </td>
                </tr>
                );
              })
            ) : (
              <tr>
                <td className="empty-cell" colSpan={columns.length + 1}>
                  No segment data available.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </section>
  );
}
